import { siteConfig } from "@/config/site";
import { seoKeywords, trustInfo } from "@/data/demo";

/**
 * Default SEO metadata for App Router Metadata API.
 * Open Graph image is also generated by `app/opengraph-image.tsx`.
 */
export const seoConfig = {
  titleTemplate: `%s | ${siteConfig.name}`,
  defaultTitle: `${siteConfig.name} | Charitable Trust in Ahmedabad`,
  description: `${trustInfo.slogan} ${trustInfo.tagline} Based in Ahmedabad since ${trustInfo.established}.`,
  canonical: siteConfig.url,
  openGraph: {
    type: "website" as const,
    locale: siteConfig.locale,
    siteName: siteConfig.name,
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: `${siteConfig.name} — ${siteConfig.slogan}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image" as const,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  keywords: [...seoKeywords],
} as const;

export type SeoConfig = typeof seoConfig;
